OPTIONS = -g
PROGRAM = main.out

all: $(PROGRAM)

run: $(PROGRAM)
	./main.out

testrun: test
	./T1.out
	./T2.out
	./T3.out
	./T4.out
	./T5.out
	./T6.out
	./T7.out
	./T8.out
	./T9.out
	./T10.out
	./T11.out
	./T12.out
	./T13.out
	./T14.out
	./T15.out
	./T16.out
	./T17.out
	./T18.out
	./T19.out
	./T20.out
	./T21.out
	./T22.out
	./T23.out
	./T24.out

$(PROGRAM): main.cpp
	g++ $(OPTIONS) main.cpp -o main.out


test: T1.cpp
	g++ $(OPTIONS) T1.cpp -o T1.out
	g++ $(OPTIONS) T2.cpp -o T2.out
	g++ $(OPTIONS) T3.cpp -o T3.out
	g++ $(OPTIONS) T4.cpp -o T4.out
	g++ $(OPTIONS) T5.cpp -o T5.out
	g++ $(OPTIONS) T6.cpp -o T6.out
	g++ $(OPTIONS) T7.cpp -o T7.out
	g++ $(OPTIONS) T8.cpp -o T8.out
	g++ $(OPTIONS) T9.cpp -o T9.out
	g++ $(OPTIONS) T10.cpp -o T10.out
	g++ $(OPTIONS) T11.cpp -o T11.out
	g++ $(OPTIONS) T12.cpp -o T12.out
	g++ $(OPTIONS) T13.cpp -o T13.out
	g++ $(OPTIONS) T14.cpp -o T14.out
	g++ $(OPTIONS) T15.cpp -o T15.out
	g++ $(OPTIONS) T16.cpp -o T16.out
	g++ $(OPTIONS) T17.cpp -o T17.out
	g++ $(OPTIONS) T18.cpp -o T18.out
	g++ $(OPTIONS) T19.cpp -o T19.out
	g++ $(OPTIONS) T20.cpp -o T20.out
	g++ $(OPTIONS) T21.cpp -o T21.out
	g++ $(OPTIONS) T22.cpp -o T22.out
	g++ $(OPTIONS) T23.cpp -o T23.out
	g++ $(OPTIONS) T24.cpp -o T24.out

testclean:
	@del -f T1.out
	@del -f T2.out
	@del -f T3.out
	@del -f T4.out
	@del -f T5.out
	@del -f T6.out
	@del -f T7.out
	@del -f T8.out
	@del -f T9.out
	@del -f T10.out
	@del -f T11.out
	@del -f T12.out
	@del -f T13.out
	@del -f T14.out
	@del -f T15.out
	@del -f T16.out
	@del -f T17.out
	@del -f T18.out
	@del -f T19.out
	@del -f T20.out
	@del -f T21.out
	@del -f T22.out
	@del -f T23.out
	@del -f T24.out

clean:
	@del -f main.out

